# Cloud vertical classes 

Function that classifies the vertical cloud cover structure based on high-mid-low cloud cover and return a mask with the cloud classes.

input: 
    -Model output of high-, mid- and low-level cloud cover
    -Provide a cloud cover threshold to clasify a layer as cloudy or not
    
output:
    -1-D matrix of the cloud class for each column
    
The 1-D matrix will consist of 8 classes as follows:
        CL1: H          CL2: M          CL3: L          CL4: HM         CL5: ML         CL6: HL        CL7: HML        CL8: clear-sky       

In [73]:
import xarray as xr
import numpy as np
from cartopy import crs as ccrs
from matplotlib import pyplot as plt
import psutil

In [74]:
# function that prints out the memory used
def print_memory(msg=None):
    process = psutil.Process()
    if (msg):
        print(msg, ':', 'memory =', np.round(process.memory_info().rss/(1024*1024)), 'MB')
    else:
        print('memory =', np.round(process.memory_info().rss/(1024*1024)), 'MB')
print_memory()

memory = 2632.0 MB


In [106]:
# we load all the timesteps for the 80km resolution
#ipath='/scratch/b/b380459/icon_4_hackathon/nawdexnwp-80km-mis-0001/'
#ifile = 'nawdexnwp-80km-mis-0001_2016092200_2d_30min_*.nc'

#ipath='/scratch/b/b380459/icon_4_hackathon/nawdexnwp-40km-mis-0001/'
#ifile = 'nawdexnwp-40km-mis-0001_2016092200_2d_30min_*.nc'

#ipath='/scratch/b/b380459/icon_4_hackathon/nawdexnwp-20km-mis-0001/'
#ifile = 'nawdexnwp-20km-mis-0001_2016092200_2d_30min_*.nc'

#ipath='/scratch/b/b380459/icon_4_hackathon/nawdexnwp-10km-mis-0001/'
#ifile = 'nawdexnwp-10km-mis-0001_2016092200_2d_30min_*.nc'

#ipath='/scratch/b/b380459/icon_4_hackathon/nawdexnwp-5km-mis-0001/'
#ifile = 'nawdexnwp-5km-mis-0001_2016092200_2d_30min_*.nc'

ipath='/scratch/b/b380459/icon_4_hackathon/nawdexnwp-2km-mis-0001/'
ifile = 'nawdexnwp-2km-mis-0001_2016092200_2d_30min_*.nc'

data = xr.open_mfdataset(ipath+ifile)
data
print_memory()

memory = 4186.0 MB


In [88]:
#test_data = data.sel(time='2016-09-22T18:00:00.000000000')
#test_data

<xarray.Dataset>
Dimensions:           (bnds: 2, height: 1, height_2: 1, lev: 1, lev_2: 1, lev_3: 1, ncells: 7920)
Coordinates:
  * lev_3             (lev_3) float64 800.0
  * lev               (lev) float64 0.0
  * height            (height) float64 10.0
  * height_2          (height_2) float64 2.0
  * lev_2             (lev_2) float64 400.0
    time              datetime64[ns] 2016-09-22T18:00:00
Dimensions without coordinates: bnds, ncells
Data variables:
    lev_bnds          (lev, bnds) float64 dask.array<chunksize=(1, 2), meta=np.ndarray>
    lev_2_bnds        (lev_2, bnds) float64 dask.array<chunksize=(1, 2), meta=np.ndarray>
    lev_3_bnds        (lev_3, bnds) float64 dask.array<chunksize=(1, 2), meta=np.ndarray>
    pres_msl          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    u_10m             (height, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    v_10m             (height, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    t_g               (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    t_2m              (height_2, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    qv_2m             (height_2, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    td_2m             (height_2, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    rh_2m             (height_2, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    accthb_t          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accsob_t          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accsod_t          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accsou_t          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accshfl_s         (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    acclhfl_s         (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accthb_s          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accthd_s          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accthu_s          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accsob_s          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accsodifu_s       (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accqhfl_s         (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accumfl_s         (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    accvmfl_s         (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    tot_prec          (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    rain_gsp_rate     (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    snow_gsp_rate     (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    graupel_gsp_rate  (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    rain_con_rate     (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    snow_con_rate     (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    cape_ml           (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    cin_ml            (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    clct              (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    clch              (lev, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    clcm              (lev_2, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    clcl              (lev_3, ncells) float32 dask.array<chunksize=(1, 7920), meta=np.ndarray>
    tqv_dia           (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    tqc_dia           (ncells) float32 dask.array<chunksize=(7920,), meta=np.ndarray>
    tqi_dia           (ncells) float32 dask.array<chunksize=(7920,), meta=np.nda

In [107]:
# mask the land areas and the domain boundaries using the openoceanmask 

def load_openoceanmask(expid):
    path  = '/scratch/b/b380459/icon_4_hackathon/'
    fname = path+'/openocean_masks/'+expid+'_openoceanmask.nc'
    return xr.open_dataset(fname)['mask_openocean']

#da_oom  = load_openoceanmask('nawdexnwp-2km-mis-0001')
#da_oom  = load_openoceanmask('nawdexnwp-80km-mis-0001')
#da_oom  = load_openoceanmask('nawdexnwp-40km-mis-0001')
#da_oom  = load_openoceanmask('nawdexnwp-20km-mis-0001')
#da_oom  = load_openoceanmask('nawdexnwp-10km-mis-0001')
#da_oom  = load_openoceanmask('nawdexnwp-5km-mis-0001')
da_oom  = load_openoceanmask('nawdexnwp-2km-mis-0001')


index = np.where(da_oom==1)[0]
data = data.isel(ncells=index)

In [108]:
# we set a threshold for the cloud cover to identify cloudy and clear sky grid boxes
thres=10

# function that gets 2-D cloud cover data of High, Mid and Low level cloud cover and creates classes for the vertical column
def cloud_class(cc_data,thres):
    # CL1: H 
    # CL2: M 
    # CL3: L 
    # CL4: HM 
    # CL5: ML 
    # CL6: HL 
    # CL7: HML 
    # CL8: clear-sky
    
    # Create the vertical cloud classes based on the threshold (thres)
    cl1     = cc_data.where((cc_data.clch>thres) & (cc_data.clcm<thres) & (cc_data.clcl<thres)) # H
    cl1_num = cl1.where(xr.ufuncs.isnan(cl1.clch),other=1)
    cl1_num = cl1_num.where((xr.ufuncs.isnan(cl1_num.clch))==False,other=0)

    cl2 = cc_data.where((cc_data.clch<thres) & (cc_data.clcm>thres) & (cc_data.clcl<thres)) # M
    cl2_num = cl2.where(xr.ufuncs.isnan(cl2.clch),other=2)
    cl2_num = cl2_num.where((xr.ufuncs.isnan(cl2_num.clch))==False,other=0)

    
    cl3 = cc_data.where((cc_data.clch<thres) & (cc_data.clcm<thres) & (cc_data.clcl>thres)) # L
    cl3_num = cl3.where(xr.ufuncs.isnan(cl3.clch),other=3)
    cl3_num = cl3_num.where((xr.ufuncs.isnan(cl3_num.clch))==False,other=0)

    
    cl4 = cc_data.where((cc_data.clch>thres) & (cc_data.clcm>thres) & (cc_data.clcl<thres)) # HM
    cl4_num = cl4.where(xr.ufuncs.isnan(cl4.clch),other=4)
    cl4_num = cl4_num.where((xr.ufuncs.isnan(cl4_num.clch))==False,other=0)

    
    cl5 = cc_data.where((cc_data.clch<thres) & (cc_data.clcm>thres) & (cc_data.clcl>thres)) # ML
    cl5_num = cl5.where(xr.ufuncs.isnan(cl5.clch),other=5)
    cl5_num = cl5_num.where((xr.ufuncs.isnan(cl5_num.clch))==False,other=0)


    cl6 = cc_data.where((cc_data.clch>thres) & (cc_data.clcm<thres) & (cc_data.clcl>thres)) # HL
    cl6_num = cl6.where(xr.ufuncs.isnan(cl6.clch),other=6)
    cl6_num = cl6_num.where((xr.ufuncs.isnan(cl6_num.clch))==False,other=0)

    
    cl7 = cc_data.where((cc_data.clch>thres) & (cc_data.clcm>thres) & (cc_data.clcl>thres)) # HML
    cl7_num = cl7.where(xr.ufuncs.isnan(cl7.clch),other=7)
    cl7_num = cl7_num.where((xr.ufuncs.isnan(cl7_num.clch))==False,other=0)

    
    cl8 = cc_data.where((cc_data.clch<thres) & (cc_data.clcm<thres) & (cc_data.clcl<thres)) # clear-sky
    cl8_num = cl8.where(xr.ufuncs.isnan(cl8.clch),other=8)
    cl8_num = cl8_num.where((xr.ufuncs.isnan(cl8_num.clch))==False,other=0)

    # we sum all the classes to one array to make a mask for the entire domain based on the cloud classification
    cloud_class_mask   = cl1+cl2+cl3+cl4+cl5+cl6+cl7+cl8 
    cloud_class_number = cl1_num+cl2_num+cl3_num+cl4_num+cl5_num+cl6_num+cl7_num+cl8_num
    return cloud_class_mask, cloud_class_number

cloud_class_array, cloud_class_number = cloud_class(data,thres)

print('###################################################################')
print('TEST OUTPUT')
print('HIGH',cloud_class_array.clch.sel(ncells=slice(4642,4660)).squeeze().values)
print('MID' ,cloud_class_array.clcm.sel(ncells=slice(4642,4660)).squeeze().values)
print('LOW' ,cloud_class_array.clcl.sel(ncells=slice(4642,4660)).squeeze().values)

print('HIGH',cloud_class_number.clch.sel(ncells=slice(4642,4660)).squeeze().values)
print('MID' ,cloud_class_number.clcm.sel(ncells=slice(4642,4660)).squeeze().values)
print('LOW' ,cloud_class_number.clcl.sel(ncells=slice(4642,4660)).squeeze().values)
print('###################################################################')

cloud_class_number

print('I save the cloud class number')
opath= '/pf/b/b380796/scratch/hackathon/george/'
np.save(opath+'cloud_class_array_thres10p_2km_alltimesteps_v2',cloud_class_number.squeeze().values)

###################################################################
TEST OUTPUT
HIGH [[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
MID [[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
LOW [[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
HIGH [[1. 1. 1. ... 1. 1. 1.]
 [6. 1. 6. ... 6. 6. 6.]
 [1. 1. 1. ... 1. 6. 1.]
 ...
 [3. 3. 3. ... 3. 3. 8.]
 [3. 3. 3. ... 3. 8. 8.]
 [6. 6. 6. ... 3. 8. 8.]]
MID [[1. 1. 1. ... 1. 1. 1.]
 [6. 1. 6. ... 6. 6. 6.]
 [1. 1. 1. ... 1. 6. 1.]
 ...
 [3. 3. 3. ... 3. 3. 8.]
 [3. 3. 3. ... 3. 8. 8.]
 [6. 6. 6. ... 3. 8. 8.]]
LOW [[1. 1